# Default Build Options
[build]
  base = "/"
  publish = "dist/"
  command = "npm run generate"

# Plausible
[[redirects]]
  from = "/pls.js"
  to = "https://analytics.joshuacooper.co.uk/js/plausible.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://analytics.joshuacooper.co.uk/api/event"
  status = 200

/js/script.js https://plausible.io/js/script.js 200
/api/event https://plausible.io/api/event 200

# Old link redirects
[[redirects]]
  from = "/portfolio/linneyregeneratecollection"
  to = "/portfolio/regenerate"
  status = 301

[[redirects]]
  from = "/demos/contineo/*"
  to = "/portfolio/contineo"
  status = 301

# Short Url Redirects
[[redirects]]
  from = "/w"
  to = "https://pbs.twimg.com/media/EYVhvZFWsAUY5gv?format=jpg&name=large"
  status = 302

[[redirects]]
  from = "/grrr"
  to = "https://www.youtube.com/watch?v=cQl7TTCfpGo"
  status = 302

[[redirects]]
  from = "/covid"
  to = "https://forms.office.com/r/P31BFfB6Fu"
  status = 302

  