# Default Build Options
[build]
  base = "/"
  publish = "dist/"
  command = "npm run generate"

# Short Url Redirects
[[redirects]]
  from = "/w"
  to = "https://pbs.twimg.com/media/EYVhvZFWsAUY5gv?format=jpg&name=large"
  status = 302

[[redirects]]
  from = "/grrr"
  to = "https://www.youtube.com/watch?v=cQl7TTCfpGo"
  status = 302

[[redirects]]
  from = "/covid"
  to = "https://forms.office.com/r/P31BFfB6Fu"
  status = 302