[build]
  base = "/"
  publish = "dist/"
  command = "npm run generate"

[[redirects]]
  from = "/w"
  to = "https://pbs.twimg.com/media/EYVhvZFWsAUY5gv?format=jpg&name=large"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200