# Default Build Options
[build]
  base = "/"
  publish = "dist/"
  command = "npm run generate"

# Old link redirects
[[redirects]]
  from = "/portfolio/linneyregeneratecollection"
  to = "/portfolio/regenerate"
  status = 301

[[redirects]]
  from = "/demos/contineo/*"
  to = "/portfolio/contineo"
  status = 301

# Short Links
[[redirects]]
  from = "/w"
  to = "https://pbs.twimg.com/media/EYVhvZFWsAUY5gv?format=jpg&name=large"
  status = 302
  